services:
  backend:
    build:
      context: ./bookreview
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped

  frontend:
    build: ./bookreviewfrontend
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    restart: unless-stopped
